buys/urls.py
from django.urls import path
from . import views


app_name = "buys"

urlpatterns = [
    path("get/<int:funding>/", views.BuyFundingView.as_view(), name="get"),
    path("myfunding/", views.SeeMyBuyFunding.as_view(), name="myfunding"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("fundings/", include("fundings.urls", namespace="fundings")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("musics/", include("musics.urls", namespace="musics")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("users/", include("users.urls", namespace="users")),
    path("buys/", include("buys.urls", namespace="buys")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fundings/urls.py
from django.urls import path
from . import views


app_name = "fundings"

urlpatterns = [
    path("create/", views.CreateFundingView.as_view(), name="create"),
    path("<int:pk>/", views.FundingDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditFundingView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.FundingPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:funding_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:funding_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

fundings/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_countries.fields import CountryField
from core import models as core_models
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class MusicType(AbstractItem):

    """MusicType Model Definition"""

    class Meta:
        verbose_name = "Music Type"


class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="funding_photos")
    funding = models.ForeignKey(
        "Funding", related_name="photos", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.caption


class song(core_models.TimeStampedModel):

    """song Model Definition"""

    caption = models.CharField(max_length=80)
    sfile = models.FileField(upload_to="musics/")
    funding = models.ForeignKey(
        "Funding", related_name="songs", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.caption


class Funding(core_models.TimeStampedModel):

    """Funding Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    price = models.IntegerField()
    funding_start = models.DateField()
    funding_end = models.DateField()
    music_stock = models.IntegerField()
    music_share = models.IntegerField()
    lyricist = models.ForeignKey(
        "users.User", related_name="fundings", on_delete=models.CASCADE
    )
    music_type = models.ManyToManyField(
        "MusicType", related_name="fundings", blank=True
    )

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #    self.city = str.capitalize(self.city)
    #    super().save(*args, **kwargs)

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.funding_start and now <= self.funding_end

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        return now > self.funding_end

    is_finished.boolean = True

    def share_price(self):
        share_price = self.price / self.music_stock
        return round(share_price, 2)

    def get_absolute_url(self):
        return reverse("fundings:detail", kwargs={"pk": self.pk})

    def funding_music(self):
        try:
            (music,) = self.songs.all()
            return music.sfile.url
        except ValueError:
            return None

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_photo(self):
        try:
            (photo,) = self.photos.all()[1:2]
            return photo.file.url
        except ValueError:
            return None

    def get_calendars(self):
        if self.funding_start.month == self.funding_end.month:
            this_month = Calendar(
                self.funding_start.year,
                self.funding_start.month,
                self.funding_end.day,
            )
        else:
            this_month = Calendar(
                self.funding_start.year,
                self.funding_start.month,
                self.funding_start.day,
            )
        next_month = Calendar(
            self.funding_end.year, self.funding_end.month, self.funding_end.day
        )
        return (this_month, next_month)

fundings/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    name = forms.CharField(initial="Anything")
    country = CountryField(default="KR").formfield()
    music_type = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.MusicType.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        funding = models.Funding.objects.get(pk=pk)
        photo.funding = funding
        photo.save()


class CreateFundingForm(forms.ModelForm):
    class Meta:
        model = models.Funding
        fields = (
            "name",
            "description",
            "country",
            "price",
            "funding_start",
            "funding_end",
            "music_stock",
            "music_share",
            "music_type",
        )

    def save(self, *args, **kwargs):
        funding = super().save(commit=False)
        return funding

fundings/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins

from . import models, forms


class HomeView(ListView):

    """HomeView Definition"""

    model = models.Funding
    paginate_by = 12
    paginate_orphans = 4
    ordering = "created"
    context_object_name = "fundings"


class FundingDetail(DetailView):

    """FundingDetail Definition"""

    model = models.Funding


class SearchView(View):

    """SearchView Definition"""

    def get(self, request):

        country = request.GET.get("country")

        if country:
            form = forms.SearchForm(request.GET)

            if form.is_valid():
                name = form.cleaned_data.get("name")
                country = form.cleaned_data.get("country")
                music_type = form.cleaned_data.get("music_type")

                filter_args = {}

                if name != "Anything":
                    filter_args["name__startswith"] = name

                filter_args["country"] = country

                fundings = models.Funding.objects.filter(**filter_args)

                for mt in music_type:
                    fundings = fundings.filter(music_type=mt)

                qs = fundings.order_by("-created")

                paginator = Paginator(qs, 12, orphans=5)

                page = request.GET.get("page", 1)

                fundings = paginator.get_page(page)

                return render(
                    request,
                    "fundings/search.html",
                    {"form": form, "fundings": fundings},
                )

        else:
            form = forms.SearchForm()

        return render(request, "fundings/search.html", {"form": form})


class EditFundingView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Funding
    template_name = "fundings/funding_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "price",
        "funding_start",
        "funding_end",
        "music_stock",
        "music_share",
        "music_type",
    )

    def get_object(self, queryset=None):
        funding = super().get_object(queryset=queryset)
        if funding.lyricist.pk != self.request.user.pk:
            raise Http404()
        return funding


class FundingPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Funding
    template_name = "fundings/funding_photos.html"

    def get_object(self, queryset=None):
        funding = super().get_object(queryset=queryset)
        if funding.lyricist.pk != self.request.user.pk:
            raise Http404()
        return funding


@login_required
def delete_photo(request, funding_pk, photo_pk):
    user = request.user
    try:
        funding = models.Funding.objects.get(pk=funding_pk)
        if funding.lyricist.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Delete")
        return redirect(reverse("fundings:photos", kwargs={"pk": funding_pk}))
    except models.Funding.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "fundings/funding_photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        funding_pk = self.kwargs.get("funding_pk")
        return reverse("fundings:photos", kwargs={"pk": funding_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    model = models.Photo
    template_name = "fundings/funding_photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("fundings:photos", kwargs={"pk": pk}))


class CreateFundingView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateFundingForm
    template_name = "fundings/funding_create.html"

    def form_valid(self, form):
        funding = form.save()
        funding.lyricist = self.request.user
        funding.save()
        form.save_m2m()
        messages.success(self.request, "Funding Uploaded")
        return redirect(reverse("fundings:detail", kwargs={"pk": funding.pk}))

templates/fundings/detail.html
{% extends "base.html" %}

{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
<div>
    <h1> {{funding.name}} </h1>
    <h3> {{funding.description}} </h3>
</div>
<div>
    <h2> 
        By: {{funding.host.username}}
        {% if funding.host.superhost %}
            (superhost)
        {% endif %}
    </h2>
    <h3> Amenities </h3>
    <ul>
        {% for a in funding.amenities.all %}
            <li> {{a}} </li>
        {% endfor %}
    </ul>
    <h3> Facilities </h3>
    <ul>
        {% for a in funding.facilities.all %}
            <li> {{a}} </li>
        {% endfor %}
    </ul>
    <h3> House Rules </h3>
    <ul>
        {% for a in funding.house_rules.all %}
            <li> {{a}} </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

templates/fundings/funding_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Funding
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/funding/funding_form.html' with form=form cta="Create Funding" %}
        
    </div>

{% endblock content %}

templates/fundings/funding_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{funding.name}}
{% endblock page_title %}

{% block content %}
    
    <div class="-mt-4 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-cover bg-center border border-gray-700" style="background-image:url({{funding.first_photo}})"></div>
        <div class="w-1/2 h-auto bg-cover bg-center border border-gray-700" style="background-image:url({{funding.get_next_photo}})"></div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mr-8 mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{funding.name}}</h4>
                    <span class="text-gray-700 font-light">{{funding.country.name}}</span>
                </div>
                <a href="{{funding.lyricist.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=funding.lyricist %}
                    <span class="mt-2 text-gray-500">{{funding.lyricist.first_name}}</span>
                </a>
            </div>
            <div class="flex border-section">
                <span class="mr-5 font-light">
                    {% for a in funding.music_type.all %}
                        {{a}}
                    {% endfor %}
                </span>
                <span class="mr-5 font-light">{{funding.music_share}} / {{funding.music_stock}}</span>
            </div>
            <p class="border-section">
                {{funding.description}}
            </p>
            {% if funding.in_progress %}
                {% if funding.lyricist != user %}
                    <a href="{% url 'buys:get' funding.pk %}" class="btn-link block mb-8">Buy Funding</a>
                {% endif %}
            {% endif %}
        </div>
        <div class="w-1/3">
            {% if funding.lyricist == user %}
                <a href="{% url 'fundings:edit' funding.pk %}" class="btn-link block mb-5">Edit Funding</a>
                {% for calendar in funding.get_calendars %}
                    <div class="mb-20">
                        <span class="text-center font-bold text-lg block mb-8">{{calendar.get_month}} / {{calendar.year}}</span>
                        <div class="cal-grid mb-4 font-semibold">
                            {% for day in calendar.day_names %}
                                <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="cal-grid">
                            {% for day in calendar.get_days %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="bg-red-500 w-full text-center rounded-lg text-white p-2">{{day}}</span>
                                    {% elif day.npast %}
                                        <span class="bg-green-500 w-full text-center rounded-lg text-white p-2">{{day}}</span>
                                    {% else %}
                                        <span class="bg-gray-100 w-full text-center rounded-lg text-gray-700 p-2">{{day}}</span>
                                    {% endif %}
                                {% else %}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                {% for calendar in funding.get_calendars %}
                    <div class="mb-20">
                        <span class="text-center font-bold text-lg block mb-8">{{calendar.get_month}} / {{calendar.year}}</span>
                        <div class="cal-grid mb-4 font-semibold">
                            {% for day in calendar.day_names %}
                                <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="cal-grid">
                            {% for day in calendar.get_days %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="bg-red-500 w-full text-center rounded-lg text-white p-2">{{day}}</span>
                                    {% elif day.npast %}
                                        <span class="bg-green-500 w-full text-center rounded-lg text-white p-2">{{day}}</span>
                                    {% else %}
                                        <span class="bg-gray-100 w-full text-center rounded-lg text-gray-700 p-2">{{day}}</span>
                                    {% endif %}
                                {% else %}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="pt-3 pb-3 border bg-red-400 font-medium text-gray-500 w-full">
        <h4 class="text-white text-6xl ml-16 mb-3">{{funding.name}}</h4>
        <span class="text-white text-3xl ml-16 mb-3">{{funding.lyricist}}</span>
        <audio controls class="w-5/6 items-center ml-16">
            <source src="{{ funding.funding_music }}" type="audio/ogg">
        </audio>
    </div>

{% endblock content %}

templates/fundings/funding_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Funding
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/funding/funding_form.html' with form=form cta="Update Funding" %}

        <div class="mt-3">
            <a href="{% url 'fundings:photos' funding.pk %}" class="text-red-400 font-bold">Edit photos</a>
        </div>
        
    </div>

{% endblock content %}

templates/fundings/funding_list.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    <div class="container mx-auto pb-10">
        
        <div class="rounded-xl -mx-40 bg-gray-800 h-50vh mt-32 mb-10 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1421217336522-861978fdf33a?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fG11c2ljfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&)"></div>

        <div class="flex flex-wrap -mx-40 mb-5">
            {% for funding in fundings %}
                {% if funding.in_progress %}
                    {% include 'mixins/funding_card.html' with funding=funding %}
                {% elif funding.is_finished %}
                    {% include 'mixins/finish_funding_card.html' with funding=funding %}
                {% else %}
                    {% include 'mixins/wait_funding_card.html' with funding=funding %}
                {% endif %}
            {% endfor %}
        </div>

        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-pink-600"> <i class="fa-solid fa-arrow-left fa-lg"></i> </a>
            {% endif %}
            
            <span class="mx-3 font-medium text-lg">Page{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-pink-600"> <i class="fa-solid fa-arrow-right fa-lg"></i> </a>
            {% endif %}
            
        </div>

    </div>

{% endblock content %}

templates/fundings/funding_photo_create.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Funding photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/funding/funding_form.html' with form=form cta="Upload Funding photo" %}

    </div>

{% endblock content %}

templates/fundings/funding_photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Edit Funding photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/funding/funding_form.html' with form=form cta="Update Funding photo" %}

    </div>

{% endblock content %}

templates/fundings/funding_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{funding.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">

        <div class="my-10 w-full">
            <a href="{% url 'fundings:add-photo' funding.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>

        {% for photo in funding.photos.all %}
            <div class = "mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class = "flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-green-500" href="{% url 'fundings:edit-photo' funding.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-500" href="{% url 'fundings:delete-photo' funding.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center mt-5">
            <a class="text-red-400 font-bold text-xl" href="{% url 'fundings:edit' funding.pk %}">Back to edit funding</a>
        </div>

    </div>

{% endblock content %}

templates/fundings/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <form method="get" action="{% url 'fundings:search' %}" class="container mx-auto w-3/5 flex-wrap">
        {{form.as_p}}
        <button class="btn text-5xl border rounded-lg bg-red-400 mt-8 mb-8 text-white">Search</button>
    </form>
        
    <h1 class="text-center text-5xl font-bold mb-8">Results</h1>

    <div class="container mx-auto flex flex-col items-center">
        <div class="flex flex-wrap -mx-40 mb-5 w-full">
            {% for funding in fundings %}
                {% include 'mixins/funding_card.html' with funding=funding %}
            {% endfor %}
        </div>
    </div>

{% endblock content %}