buys/urls.py
from django.urls import path
from . import views


app_name = "buys"

urlpatterns = [
    path("get/<int:funding>/", views.BuyFundingView.as_view(), name="get"),
    path("myfunding/", views.SeeMyBuyFunding.as_view(), name="myfunding"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("fundings/", include("fundings.urls", namespace="fundings")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("musics/", include("musics.urls", namespace="musics")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("users/", include("users.urls", namespace="users")),
    path("buys/", include("buys.urls", namespace="buys")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fundings/urls.py
from django.urls import path
from . import views


app_name = "fundings"

urlpatterns = [
    path("create/", views.CreateFundingView.as_view(), name="create"),
    path("<int:pk>/", views.FundingDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditFundingView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.FundingPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:funding_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:funding_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

musics/urls.py
from django.urls import path
from . import views

app_name = "musics"

urlpatterns = [
    path("create/", views.CreateMusicView.as_view(), name="create"),
    path("<int:pk>/", views.MusicDetail.as_view(), name="mdetail"),
    path("<int:pk>/edit/", views.EditMusicView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.MusicPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:music_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:music_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

templates/mixins/finish_funding_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'fundings:detail' funding.pk %}">
    <div class="w-full h-64 bg-cover bg-center rounded-md mb-3" style="background-image: url({{funding.first_photo}});"></div>
    <div class="flex justify-between mb-2">
        <div class="border bg-red-400 border-red-400 text-black rounded py-px px-1">
            <span class="uppercase font-medium text-white">finish funding</span>
        </div>
        <div>
            <i class="fa-solid fa-dollar-sign text-green-600 mx-1"></i>{{funding.share_price}}
        </div>
    </div>
    <span class="text-balck w-11/12 block truncate">{{funding.name}}</span>
    </a>
</div>

templates/mixins/funding_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'fundings:detail' funding.pk %}">
    <div class="w-full h-64 bg-cover bg-center rounded-md mb-3" style="background-image: url({{funding.first_photo}});"></div>
    <div class="flex justify-between mb-2">
        <div class="border bg-green-500 border-green-500 text-black rounded py-px px-1">
            <span class="uppercase font-medium text-white">left funding</span>
            <span class="text-white font-light">{{funding.music_share}} / {{funding.music_stock}}</span>
        </div>
        <div>
            <i class="fa-solid fa-dollar-sign text-green-600 mx-1"></i>{{funding.share_price}}
        </div>
    </div>
    <span class="text-balck w-11/12 block truncate">{{funding.name}}</span>
    </a>
</div>

templates/mixins/music_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'musics:mdetail' music.pk %}">
    <div class="w-full h-64 bg-cover bg-center rounded-md mb-3" style="background-image: url({{music.first_photo}});"></div>
    <div class="flex justify-between mb-2">
        <div class="border border-black text-black rounded py-px px-1">
            <span> {{music.lyricist}} </span>
        </div>
        <div>
            <i class="fas fa-star text-yellow-300 mx-1"></i>{{music.total_rating}}
        </div>
    </div>
    <span class="text-balck w-11/12 block truncate">{{music.name}}</span>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-cover bg-center" style="background-image: url({{user.avatar.url}});"></div>
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-gray-400 rounded-full text-white flex justify-center items-center overflow-hidden">
        <span class="{{text|default:'text-3xl'}}">{{user.first_name|first}}</span>
    </div>
{% endif %}

templates/mixins/wait_funding_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'fundings:detail' funding.pk %}">
    <div class="w-full h-64 bg-cover bg-center rounded-md mb-3" style="background-image: url({{funding.first_photo}});"></div>
    <div class="flex justify-between mb-2">
        <div class="border bg-gray-600 border-gray-600 text-black rounded py-px px-1">
            <span class="uppercase font-medium text-white">finish funding</span>
        </div>
        <div>
            <i class="fa-solid fa-dollar-sign text-green-600 mx-1"></i>{{funding.share_price}}
        </div>
    </div>
    <span class="text-balck w-11/12 block truncate">{{funding.name}}</span>
    </a>
</div>