buys/urls.py
from django.urls import path
from . import views


app_name = "buys"

urlpatterns = [
    path("get/<int:funding>/", views.BuyFundingView.as_view(), name="get"),
    path("myfunding/", views.SeeMyBuyFunding.as_view(), name="myfunding"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("fundings/", include("fundings.urls", namespace="fundings")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("musics/", include("musics.urls", namespace="musics")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("users/", include("users.urls", namespace="users")),
    path("buys/", include("buys.urls", namespace="buys")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("toggle/<int:music_pk>", views.toggle_music, name="toggle-music"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

musics/urls.py
from django.urls import path
from . import views

app_name = "musics"

urlpatterns = [
    path("create/", views.CreateMusicView.as_view(), name="create"),
    path("<int:pk>/", views.MusicDetail.as_view(), name="mdetail"),
    path("<int:pk>/edit/", views.EditMusicView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.MusicPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:music_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:music_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

musics/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class MusicType(AbstractItem):

    """MusicType Model Definition"""

    class Meta:
        verbose_name = "Music Type"


class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="music_photos")
    music = models.ForeignKey("Music", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class song(core_models.TimeStampedModel):

    """song Model Definition"""

    caption = models.CharField(max_length=80)
    sfile = models.FileField(upload_to="musics/")
    music = models.ForeignKey("Music", related_name="songs", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Music(core_models.TimeStampedModel):

    """Music Model Definition"""

    name = models.CharField(max_length=140)
    lyricist = models.ForeignKey(
        "users.User", related_name="musics", on_delete=models.CASCADE
    )
    description = models.TextField()
    price = models.IntegerField(default=0)
    music_type = models.ManyToManyField("MusicType", related_name="musics", blank=True)

    def __str__(self):
        return self.name

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_photo(self):
        try:
            (photo,) = self.photos.all()[1:2]
            return photo.file.url
        except ValueError:
            return None

    def get_absolute_url(self):
        return reverse("musics:mdetail", kwargs={"pk": self.pk})

    def music_music(self):
        try:
            (music,) = self.songs.all()
            return music.sfile.url
        except ValueError:
            return None

musics/forms.py
from django import forms
from . import models


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        music = models.Music.objects.get(pk=pk)
        photo.music = music
        photo.save()


class CreateMusicForm(forms.ModelForm):
    class Meta:
        model = models.Music
        fields = (
            "name",
            "description",
            "music_type",
        )

    def save(self):
        music = super().save(commit=False)
        return music

musics/views.py
from django.http import Http404
from django.views.generic import DetailView, UpdateView, FormView
from django.shortcuts import redirect, reverse
from users import mixins as user_mixins
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import models, forms

# Create your views here.


class MusicDetail(DetailView):

    """MusicDetail Definition"""

    model = models.Music


class EditMusicView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Music
    template_name = "musics/music_edit.html"
    fields = (
        "name",
        "description",
        "music_type",
    )

    def get_object(self, queryset=None):
        music = super().get_object(queryset=queryset)
        if music.lyricist.pk != self.request.user.pk:
            raise Http404()
        return music


class MusicPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Music
    template_name = "musics/music_photos.html"

    def get_object(self, queryset=None):
        music = super().get_object(queryset=queryset)
        if music.lyricist.pk != self.request.user.pk:
            raise Http404()
        return music


@login_required
def delete_photo(request, music_pk, photo_pk):
    user = request.user
    try:
        music = models.Music.objects.get(pk=music_pk)
        if music.lyricist.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Delete")
        return redirect(reverse("musics:photos", kwargs={"pk": music_pk}))
    except models.Music.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "musics/music_photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        music_pk = self.kwargs.get("music_pk")
        return reverse("musics:photos", kwargs={"pk": music_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    model = models.Photo
    template_name = "musics/music_photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("musics:photos", kwargs={"pk": pk}))


class CreateMusicView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateMusicForm
    template_name = "musics/music_create.html"

    def form_valid(self, form):
        music = form.save()
        music.lyricist = self.request.user
        music.save()
        form.save_m2m()
        messages.success(self.request, "Music Uploaded")
        return redirect(reverse("musics:mdetail", kwargs={"pk": music.pk}))

templates/musics/music_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Music
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/music/music_form.html' with form=form cta="Create Music" %}

    </div>

{% endblock content %}

templates/musics/music_detail.html
{% extends "base.html" %}
{% load on_favs %}

{% block page_title %}
    {{music.name}}
{% endblock page_title %}

{% block content %}

    <div class="-mt-4 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-cover bg-center border border-gray-700" style="background-image:url({{music.first_photo}})"></div>
        <div class="w-1/2 h-auto bg-cover bg-center border border-gray-700" style="background-image:url({{music.get_next_photo}})"></div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mr-8 mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{music.name}}</h4>
                    <span class="text-gray-700 font-light">{{music.lyricist}}</span>
                </div>
                <a href="{{music.lyricist.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=music.lyricist %}
                    <span class="mt-2 text-gray-500">{{music.lyricist.first_name}}</span>
                </a>
            </div>
            {% if music.lyricist != user %}
                {% on_favs music as on_favs_boolean %}
                {% if on_favs_boolean %}
                    <a class="block mb-10 w-2/5 text-red-400 font-bold" href="{% url 'lists:toggle-music' music.pk %}?action=remove">Remove from Favorite Music</a>
                {% else %}
                    <a class="block mb-10 w-2/5 text-red-400 font-bold" href="{% url 'lists:toggle-music' music.pk %}?action=add">Save to Favorite Music</a>
                {% endif %}
            {% endif %}
            <div class="flex border-section">
                <span class="mr-5 font-light">
                    {% for a in music.music_type.all %}
                        {{a}}
                    {% endfor %}
                </span>
            </div>
            <p class="border-section">
                {{music.description}}
            </p>
            
        </div>
        <div class="w-1/3">
            {% if music.lyricist == user %}
                <a href="{% url 'musics:edit' music.pk %}" class="btn-link block mb-8">Edit Music</a>
            {% else %}
                <a href="{% url 'reviews:create' music.pk %}" class="btn-link block mb-8">Write a Review</a>
            {% endif %}
            <div>
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-yellow-300"></i>
                        <span class="font-bold text-xl">{{music.total_rating}}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-300 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{music.reviews.count}}</span>
                        <span>review{{music.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-8">
                    {% for review in music.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w="w-12 h-12" text="text-xl" %}
                                </div>
                                <div class="flex flex-col ml-3">
                                    <span class="font-bold">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="pt-3 pb-3 border bg-red-400 font-medium text-gray-500 w-full">
        <h4 class="text-white text-6xl ml-16 mb-3">{{music.name}}</h4>
        <span class="text-white text-3xl ml-16 mb-3">{{music.lyricist}}</span>
        <audio controls class="w-5/6 items-center ml-16">
            <source src="{{ music.music_music }}" type="audio/ogg">
        </audio>
    </div>

{% endblock content %}

templates/musics/music_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Music
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/music/music_form.html' with form=form cta="Update Music" %}

        <div class="mt-3">
            <a href="{% url 'musics:photos' music.pk %}" class="text-red-400 font-bold">Edit photos</a>
        </div>

    </div>

{% endblock content %}

templates/musics/music_photo_create.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Music photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/music/music_form.html' with form=form cta="Upload Music photo" %}

    </div>

{% endblock content %}

templates/musics/music_photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Edit Music photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/music/music_form.html' with form=form cta="Update Music photo" %}


    </div>

{% endblock content %}

templates/musics/music_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{music.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">

        <div class="my-10 w-full">
            <a href="{% url 'musics:add-photo' music.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>

        {% for photo in music.photos.all %}
            <div class = "mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class = "flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-green-500" href="{% url 'musics:edit-photo' music.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-500" href="{% url 'musics:delete-photo' music.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center mt-5">
            <a class="text-red-400 font-bold text-xl" href="{% url 'musics:edit' music.pk %}">Back to edit music</a>
        </div>

    </div>

{% endblock content %}

templates/musics/music_review.html
{% extends 'base.html' %}

{% block page_title %}
    Create Review
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 sm:w-3/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/review/review_form.html' with form=form cta="Write a Review" %}

    </div>

{% endblock content %}